/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.java.compiler;

public class App {
    public String getGreeting() {
        String toy = "a toy".toUpperCase();
        return toy; 
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
