/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gradle.java.compiler;

import java.io.IOException;

public class App {
  public static void main(String[] args) throws IOException {
    System.out.println("Starting Lox Repl");      
    Lox.main(args);
  }
}
