[package]
name = "rustcompc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name = "rustcompc_tests"
path = "tests/lexer_tests.rs"